// The WFRP4e "random talents" table (d100 → talent), generated by build-wfrp-races.mjs.
// Used to roll a race's starting random talents and for the manual roller.
import table from '@/data/wfrp-random-talents.json';

type Entry = { min: number; max: number; name: string };
const TABLE = table as Entry[];

/** Roll a single random talent name for a d100 result, or null if the roll is uncovered. */
export function rollRandomTalentName(rollD100: () => number): string | null {
  const roll = rollD100();
  return TABLE.find((e) => roll >= e.min && roll <= e.max)?.name ?? null;
}

/**
 * Roll `count` distinct random talents (re-rolling names already in `exclude` or already
 * rolled, as the rules require). Bounded so a pathological roller can't loop forever.
 */
export function rollRandomTalents(count: number, rollD100: () => number, exclude: string[] = []): string[] {
  const have = new Set(exclude.map((s) => s.toLowerCase()));
  const out: string[] = [];
  let guard = 0;
  while (out.length < count && guard < count * 20 + 40) {
    guard++;
    const name = rollRandomTalentName(rollD100);
    if (name && !have.has(name.toLowerCase())) {
      have.add(name.toLowerCase());
      out.push(name);
    }
  }
  return out;
}
