// Bundled WFRP4e book reference content, generated by scripts/build-wfrp-content.mjs.
// Seeded into the content_library SQLite table on first launch (see queries.ts).
//
// Bump CONTENT_SEED_VERSION whenever the JSON is regenerated to force a re-seed.
import skill from './skill.json';
import talent from './talent.json';
import spell from './spell.json';
import prayer from './prayer.json';
import trapping from './trapping.json';
import quality from './quality.json';
import mutation from './mutation.json';
import creature_trait from './creature_trait.json';
import rune from './rune.json';
import career from './career.json';
import critical_wound from './critical_wound.json';

export const CONTENT_SEED_VERSION = '2';

export type ContentCategory =
  | 'skill' | 'talent' | 'spell' | 'prayer' | 'trapping'
  | 'quality' | 'mutation' | 'creature_trait' | 'rune' | 'career'
  | 'critical_wound';

export type ContentRecord = {
  id: string;
  name: string;
  characteristic?: string | null;
  [key: string]: unknown;
};

export const CONTENT_SOURCES: Record<ContentCategory, ContentRecord[]> = {
  skill: skill as ContentRecord[],
  talent: talent as ContentRecord[],
  spell: spell as ContentRecord[],
  prayer: prayer as ContentRecord[],
  trapping: trapping as ContentRecord[],
  quality: quality as ContentRecord[],
  mutation: mutation as ContentRecord[],
  creature_trait: creature_trait as ContentRecord[],
  rune: rune as ContentRecord[],
  career: career as ContentRecord[],
  critical_wound: critical_wound as ContentRecord[],
};
