// Starting trappings ("objects") by class, generated by scripts/build-wfrp-races.mjs
// from json_book_information/races_starting_attributes.json. In WFRP4e starting trappings
// come from a character's CLASS (derived from their career), not their race — so these are
// granted when a career is selected (see CareerPicker), keyed by the career's class index.
import data from './wfrp-class-trappings.json';

export type ClassTrappingItem = { name: string; qty: number; enc: number; notes?: string };

/** Trappings for a career's `class` index (0–7), or [] if out of range. */
export function classTrappingsForClass(classIndex: number | undefined): ClassTrappingItem[] {
  if (classIndex == null) return [];
  const key = data.classKeys[classIndex];
  if (!key) return [];
  return ((data.byClass as Record<string, ClassTrappingItem[]>)[key]) ?? [];
}
