// Built-in WFRP4e base races. Generated by scripts/build-wfrp-races.mjs from the
// user-maintained json_book_information/races_starting_attributes.json (re-run that
// script after editing the source). `modifiers` are the racial attribute base values
// (the "+X" on top of each 2d10 roll); skills/talents are the racial starting grants.
// Always shown in the Race picker; custom races live in the settings library. Adding a
// race needs no change to character-creation logic.
import raw from './wfrp-races.json';
import type { WfrpSpeciesDef } from '@/types/wfrp4e';

export const BASE_RACES: WfrpSpeciesDef[] = raw as WfrpSpeciesDef[];
